---
- name: Create SSL directory.
  file:
    path: /etc/nginx/ssl/
    state: directory

- name: Create site directory
  file:
    path: /var/www/{{site_url}}
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/nginx/ssl/{{ site_url }}.key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/nginx/ssl/{{ site_url }}.csr
    privatekey_path: /etc/nginx/ssl/{{ site_url }}.key
    common_name: "{{ site_url }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/nginx/ssl/{{ site_url }}.crt
    privatekey_path: /etc/nginx/ssl/{{ site_url }}.key
    csr_path: /etc/nginx/ssl/{{ site_url }}.csr
    provider: selfsigned
